### ISSUE TITLE
[ Feature Request ] is it possible to add `"" / '' / ``" highlight?

### ISSUE THREAD

**Issue by NEX-S** [monkoose/matchparen.nvim#17]
it seems the vim regex engine cant highlight the quote correctly, I don't know if treesitter can highlight it

**Comment by monkoose** [comment]
Sorry, not planning to add something like that in the foreseeable future.
Because:
 - much harder to implement (no difference between closing/opening part)
 - plugin supports both vim syntax highlighting and treesitter (of course some highlighting can be done only for one of them, but i have focus on other things right now).
 - I even didn't finish highlighting of parentheses when inside them (and not only on one of them) and proper work of text-objects like `i(` or `a[` etc. So if something would be done with this plugin, then it would be this features first.
