### ISSUE TITLE
default MatchParen is active

### ISSUE THREAD

**Issue by JoseConseco** [monkoose/matchparen.nvim#9]
I get error that default MatchParen is active- even though, if I understand this correctly, I have set: vim.g.loaded_matchparen = 1 - which should disable default matchParent right?
```lua
  use {
    "monkoose/matchparen.nvim",
    disable = false, -- what idt does? - faster highlight (), [], & {} compared to vim builtin matchparen
    config = function()
      vim.g.loaded_matchparen = 1
      require("matchparen").setup()
    end,
  }

```

**Comment by monkoose** [comment]
Hello. I have added this check recently, because in my knowledge not all the users properly load lua plugins. Order should be as:
user plugins and only then builtin plugins. You can check the order with `:scriptnames`.
So its definitely improper neovim config on your side. If you don't know how to fix it, link me to your dotfiles. 

> I understand this correctly, I have set: `vim.g.loaded_matchparen = 1` - which should disable default matchParent right?

You don't need to set it, plugin does it for you. And yes in theory it should disable default matchParen, but as I said because of improper ordering default matchParen plugin loaded before your config files, so neither this plugin nor this option in your config do what it should.

As quick fix put this option into your `init.lua` or `init.vim` in a main config directory. But consider to fix you config. Require packer as soon as possible from you `init.lua`

**Comment by JoseConseco** [comment]
Ok, thx for info. The error was caused by not disabled 'andymass/vim-matchup' plug. I get no error after disabling it. Sorry for trouble. Closing
